name: Publish MkDocs to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Copy README.md to docs/index.md
        shell: pwsh
        run: | # powershell
          Copy-Item -Path 'README.md' -Destination 'docs/index.md'
      - name: Deploy MkDocs to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
